export default [
  'Counter-Strike 2',
  'Dota 2',
  'PUBG: BATTLEGROUNDS',
  'Palworld',
  'Apex Legends',
  'HELLDIVERS™ 2',
  'Grand Theft Auto V',
  "Baldur's Gate 3",
  'Rust',
  'Granblue Fantasy: Relink',
  'War Thunder',
  'Call of Duty®',
  'Lethal Company',
  'Monster Hunter: World',
  'Enshrouded',
  'Warframe',
  "Tom Clancy's Rainbow Six Siege",
  'Spacewar',
  "Sid Meier's Civilization VI",
  'Deep Rock Galactic: Survivor',
  'Battlefield™ V',
  'EA SPORTS FC™ 24',
  'Cyberpunk 2077',
  'DayZ',
  'Hearts of Iron IV',
  'Lost Ark',
  'Euro Truck Simulator 2',
  'Stardew Valley',
  'Dead by Daylight',
  "Don't Starve Together",
  'Overwatch® 2',
  'Farming Simulator 22',
  'Destiny 2',
  '7 Days to Die',
  'Terraria',
  'ARK: Survival Evolved',
  'Project Zomboid',
  'Left 4 Dead 2',
  'Last Epoch',
  "Garry's Mod",
  "Hero's Land",
  'Mount & Blade II: Bannerlord',
  'THE FINALS',
  'Persona 3 Reload',
  'Valheim',
  'The Binding of Isaac: Rebirth',
  'TEKKEN 8',
  'Total War: WARHAMMER III',
  'RimWorld',
  'Goose Goose Duck',
  'Age of Empires II: Definitive Edition',
  'Hunt: Showdown',
  'Black Desert',
  "No Man's Sky",
  'Path of Exile',
  'SCUM',
  'Europa Universalis IV',
  'Crusader Kings III',
  'Rocket League',
  'Battlefield 1 ™',
  "Sid Meier's Civilization V",
  'ARK: Survival Ascended',
  'Like a Dragon: Infinite Wealth',
  'Battlefield™ 2042',
  'Phasmophobia',
  'Fallout 4',
  'FINAL FANTASY XIV Online',
  'Squad',
  'Age of Empires IV: Anniversary Edition',
  'Forza Horizon 5',
  'Hogwarts Legacy',
  'Factorio',
  'Crab Game',
  'PAYDAY 2',
  'Football Manager 2023',
  'The Elder Scrolls Online',
  'BeamNG.drive'
]
